force-app/main/default/objects/WeatherApiConfig__c/WeatherApiConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Weather API Config</label>
</CustomObject>

force-app/main/default/objects/WeatherApiConfig__c/fields/ApiKey__c.field-meta.xml
<CustomField>
    <fullName>ApiKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>API Key</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/WeatherApiServiceTest.cls
@isTest
private class WeatherApiServiceTest {
    private static final String TEST_ZIP = '94105';
    private static final String TEST_API_KEY = '12345';

    static void setup() {
        WeatherApiConfig__c config = new WeatherApiConfig__c(ApiKey__c = TEST_API_KEY);
        insert config;
    }

    @isTest
    static void getCurrentWeatherQueryMissingErrorTest() {
        setup();
        Test.startTest();
        Exception ex;
        try {
            WeatherApiService.getCurrentWeather(null);
        } catch (Exception e) {
            ex = e;
        }
        Test.stopTest();
        System.assertNotEquals(null, ex);
        System.assertEquals(WeatherApiService.QUERY_PARAMETER_MISSING, ex.getMessage());
    }

    @isTest
    static void getCurrentWeatherApiKeyMissingErrorTest() {
        Test.startTest();
        Exception ex;
        try {
            WeatherApiService.getCurrentWeather(TEST_ZIP);
        } catch (Exception e) {
            ex = e;
        }
        Test.stopTest();
        System.assertNotEquals(null, ex);
        System.assertEquals(WeatherApiService.API_KEY_MISSING, ex.getMessage());
    }

    @isTest
    static void getCurrentWeatherApiErrorWithMessageTest() {
        setup();
        Test.setMock(HttpCalloutMock.class, new WeatherApiCalloutMock(400, 'Bad Request', WeatherApiCalloutMock.GET_CURRENT_ERROR));
        Test.startTest();
        Exception ex;
        try {
            WeatherApiService.getCurrentWeather(TEST_ZIP);
        } catch (Exception e) {
            ex = e;
        }
        Test.stopTest();
        System.assertNotEquals(null, ex);
        System.assert(WeatherApiCalloutMock.GET_CURRENT_ERROR.contains(ex.getMessage()));
    }

    @isTest
    static void getCurrentWeatherApiErrorNoMessageTest() {
        setup();
        Test.setMock(HttpCalloutMock.class, new WeatherApiCalloutMock(400, 'Bad Request', '{}'));
        Test.startTest();
        Exception ex;
        try {
            WeatherApiService.getCurrentWeather(TEST_ZIP);
        } catch (Exception e) {
            ex = e;
        }
        Test.stopTest();
        System.assertNotEquals(null, ex);
        System.assertEquals(
            String.format(
                WeatherApiService.ENEXPECTED_STATUS_CODE, 
                new String[]{
                    String.valueOf(400), 
                    'Bad Request'
                }
            ),
            ex.getMessage()
        );
    }

    @isTest
    static void getCurrentWeatherSuccessTest() {
        setup();
        Test.setMock(HttpCalloutMock.class, new WeatherApiCalloutMock(200, 'OK', WeatherApiCalloutMock.GET_CURRENT_SUCCESS));
        Test.startTest();
        WeatherApiResponseWrapper result = WeatherApiService.getCurrentWeather(TEST_ZIP);
        Test.stopTest();
        System.assert(result != null && result.current != null && result.location != null);
    }
}