force-app/main/default/objects/WeatherApiConfig__c/WeatherApiConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Weather API Config</label>
</CustomObject>

force-app/main/default/objects/WeatherApiConfig__c/fields/ApiKey__c.field-meta.xml
<CustomField>
    <fullName>ApiKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>API Key</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WeatherApiConfig__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <defaultValue>&apos;http://api.weatherapi.com/v1/current.json?key={0}&amp;q={1}&apos;</defaultValue>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WeatherApiService.cls
public with sharing class WeatherApiService {
    private static final String GET_METHOD = 'GET';
    private static final String UTF8_ENCODING_SCHEME = 'UTF-8';
    
    @TestVisible
    private static final String QUERY_PARAMETER_MISSING = 'Query parameter is missing.';
    @TestVisible    
    private static final String API_KEY_OR_ENDPOINT_MISSING = 'API Key or Endpoint is missing. Check Weather API Config Custom Settings.';
    @TestVisible
    private static final String ENEXPECTED_STATUS_CODE = 'The status code returned was not expected: {0} {1}';

    public static WeatherApiResponseWrapper getCurrentWeather(String query) {
        if (String.isBlank(query)) {
            throw new WeatherApiException(QUERY_PARAMETER_MISSING);
        }
        WeatherApiConfig__c config = WeatherApiConfig__c.getInstance();
        if (config == null || String.isBlank(config.ApiKey__c) || String.isBlank(config.Endpoint__c)) {
            throw new WeatherApiException(API_KEY_OR_ENDPOINT_MISSING);
        }
        HttpRequest req = createRequest(config, query);
        return sendRequest(req);
    }

    private static HttpRequest createRequest(WeatherApiConfig__c config, String query) {
        HttpRequest req = new HttpRequest();
        req.setEndpoint(
            String.format(
                config.Endpoint__c,
                new String[]{
                    EncodingUtil.urlEncode(config.ApiKey__c, UTF8_ENCODING_SCHEME),
                    EncodingUtil.urlEncode(query, UTF8_ENCODING_SCHEME)
                }
            )
        );
        req.setMethod(GET_METHOD);
        return req;
    }

    private static WeatherApiResponseWrapper sendRequest(HttpRequest req) {
        HttpResponse res = new Http().send(req);
        WeatherApiResponseWrapper result;
        if (res.getStatusCode() == 200) {
            result = (WeatherApiResponseWrapper) JSON.deserialize(res.getBody(), WeatherApiResponseWrapper.class);
        } else {
            String errorMessage;
            try {
                result = (WeatherApiResponseWrapper) JSON.deserialize(res.getBody(), WeatherApiResponseWrapper.class);
                if (result.error == null || String.isBlank(result.error.message)) {
                    throw new WeatherApiException();
                }
                errorMessage = result.error.message;
            } catch (Exception e) {
                errorMessage = String.format(
                    ENEXPECTED_STATUS_CODE, 
                    new String[]{
                        String.valueOf(res.getStatusCode()), 
                        res.getStatus()
                    }
                );
            }
            throw new WeatherApiException(errorMessage);
        }
        return result;
    }

    public class WeatherApiException extends Exception { }
}